config/routes.rb
Rails.application.routes.draw do
  devise_for :admins do
  	resources :homes
  end
  resources :phones, :shoes
  
  root 'homes#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/phone.rb
class Phone < ApplicationRecord
	mount_uploader :p_pic, PPicUploader
end

app/models/shoe.rb
class Shoe < ApplicationRecord
	mount_uploader :s_pic, SPicUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	before_action :authenticate_admin!
	def index
		@homes = Home.all
	end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
	def index
		@phones = Phone.all
	end
	def new
		@phone = Phone.new
	end
	def show
		@phone = Phone.find(params[:id])
	end	
	def edit
		@phone = Phone.find(params[:id])
	end
	def create
		@phone = Phone.create(phone_params)
  		if @phone.save
    		redirect_to phones_path(id: @phone.id)
  		else
    		render 'new'
  		end
	end
	private
  	def phone_params
    	params.require(:phone).permit(:p_pic, :p_name, :p_desc, :p_prize)
  	end
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
	def index
		@shoes = Shoe.all
	end
	def new
		@shoe = Shoe.new
	end
	def show
		@shoe = Shoe.find(params[:id])
	end	
	def edit
		@shoe = Shoe.find(params[:id])
	end
	def create
		@shoe = Shoe.create(shoe_params)
  		if @shoe.save
    		redirect_to shoes_path(id: @shoe.id)
  		else
    		render 'new'
  		end
	end
	private
  	def shoe_params
    	params.require(:shoe).permit(:s_pic, :s_name, :s_desc, :s_prize)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/homes/index.html.erb
<h1 class=head>E-Kart</h1>
<div class="dropdown">
  <button class="dropbtn">Category</button>
  <div class="dropdown-content">
  	<%= link_to "Shoes", shoes_path %>
  	<%= link_to "Phones", phones_path %>
  </div>
</div>
<br>
<div>
	<%= button_to "logout", destroy_admin_session_path, method: :delete  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ecom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
       <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/phones/new.html.erb
<%= form_with scope: :phone, url: :phones do |f| %>
 
  <div class="pfield">
    <%= f.label :Phone_Name %><br>
    <%= f.text_field :p_name %>
  </div>
  <div class="pfield">
    <%= f.label :Description %><br>
    <%= f.text_area :p_desc %>
  </div>
  <div class="pfield">
    <%= f.label :Phone_Image %><br>
    <%= f.file_field :p_pic %>
  </div>
  <div class="pfield">
    <%= f.label :Phone_Prize %><br>
    <%= f.text_field :p_prize%>
  </div>
  <div class="p_actions">
    <%= f.submit :Add_Phone%>
  </div>
<% end %>

app/views/phones/show.html.erb
<p>
 <%= image_tag @phone.p_pic.thumb.url %>
</p>
<p>
	<tr>
		<td><%= @phone.p_name %></td>
	</tr>
	<tr>
		<td><%= @phone.p_desc %></td>
	</tr> 
</p>
<p>
  <%= @phone.p_prize %>
</p>

<br>

app/views/shoes/index.html.erb
<h1 class=head>Shoe</h1>
<%= link_to 'ADD', new_shoe_path%>
<table>
  <tr>
    <th>Shoe Image</th>
    <th>Shoe Name</th>
    <th>Shoe Description</th>
    <th>Shoe Prize</th>
  </tr>
  <% @shoes.each do |shoe| %>
  <tr>
      <td><%= image_tag(shoe.s_pic.url,size: "95x95") %></td>
      <td><%= shoe.s_name %></td>
      <td><%= shoe.s_desc %></td>
      <td><%= shoe.s_prize %></td>
      <td><%= link_to 'Show', shoe %></td>
  </tr>
  <% end %>
  <tr>
  	<%= link_to 'Back', root_path%>

</table>

app/views/shoes/new.html.erb
<%= form_with scope: :shoe, url: :shoes do |f| %>
 
  <div class="sfield">
    <%= f.label :Shoe_Name %><br>
    <%= f.text_field :s_name %>
  </div>
  <div class="sfield">
    <%= f.label :Description %><br>
    <%= f.text_area :s_desc %>
  </div>
  <div class="sfield">
    <%= f.label :Shoe_Image %><br>
    <%= f.file_field :s_pic %>
  </div>
  <div class="sfield">
    <%= f.label :Shoe_Prize %><br>
    <%= f.text_field :s_prize%>
  </div>
  <div class="s_actions">
    <%= f.submit :Add_Shoe%>
  </div>
<% end %>

app/views/shoes/show.html.erb
<tr>
	<td><%= image_tag(@shoe.s_pic.url,size: "150x150") %></td>
	<td>
		<tr>
			<td><%= @shoe.s_name %></td>
		</tr>
		<br><br>
		<tr>
			<td><%= @shoe.s_desc %></td>
		</tr> 
	</td>
	<td>
 		 <%= @shoe.s_prize %>
	</td>
	<div class=box><%= link_to 'Show All', shoes_path %></div>
</tr>